version: '{build}'

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

configuration:
   - Debug
   - Release

before_build:
- cmake . -Bbuild -G "Visual Studio 15 2017 Win64"

build_script:
- cmake --build build

after_build:
- cmake --build build --target check
