version: '{build}'

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

environment:
   matrix:
      - CMAKE_BUILD_TYPE: Debug
      - CMAKE_BUILD_TYPE: Release

before_build:
- cmake . -Bbuild -G "Visual Studio 15 2017 Win64"

build_script:
- cmake --build build --config %CMAKE_BUILD_TYPE%

after_build:
- cmake --build build --target check --config  %CMAKE_BUILD_TYPE%
